apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 2
  template:
    metadata: 
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest